name: Publish to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        mkdir gh-pages
        cp -r ./src/index.html* ./gh-pages
        cd gh-pages
        git init
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@git
